// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2NrxPpXFFNBho6ZEWhE2rq1Vjr9Mrs8',
    appId: '1:733864177789:web:1b0989e231cb72f9758114',
    messagingSenderId: '733864177789',
    projectId: 'untitled-5c38f',
    authDomain: 'untitled-5c38f.firebaseapp.com',
    storageBucket: 'untitled-5c38f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN7uA497F6pV5bzd2_egmBQKM62kIi5Xo',
    appId: '1:733864177789:android:34bd95c927628b96758114',
    messagingSenderId: '733864177789',
    projectId: 'untitled-5c38f',
    storageBucket: 'untitled-5c38f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEd4juc-juHb2etV3_jcEug6pg5hxCQPo',
    appId: '1:733864177789:ios:11ef166ea904eae9758114',
    messagingSenderId: '733864177789',
    projectId: 'untitled-5c38f',
    storageBucket: 'untitled-5c38f.appspot.com',
    iosBundleId: 'com.example.ayurbot',
  );
}
